### ISSUE TITLE
High CS Buff

### ISSUE THREAD

**Issue by kipster16** [tsunyoku/akatsuki-pp#16]
cs8 6* are incredibly harder than cs4 9* so possibly base a buff on cs based on hit radius (i.e the lower the radius is the higher the buff is)

**Comment by kipster16** [comment]
> do you think it should reach a certain threshold before being applied, or should it be applied (but scaled) in all cases?
honestly, no. if a threshold was applied, then cs0 maps would give more than they should, and i really wouldn't want to promote playing low cs maps as it 99% of the time causes a skill decrease

> i feel like this could accidentally buff maps that are regular cs e.g like 4 for no reason, so there needs to be some base cs before it is buffed imo
I agree. I think the base should be cs 4.2 (or hit object radius 35.6), but a base of 4 (or hit object radius 36.49) would be good too

**Comment by kittsun** [comment]
james is opening a poll on what the base should be

**Comment by Mokobe-osu** [comment]
maybe we could see a change starting around cs 5.5?

**Comment by kittsun** [comment]
Agreed, I'm suggesting 5.7-5.8 as inbetween 5.5 and 6 is what we're aiming for. That's when it starts to get difficult to aim objects imo

**Comment by tsunyoku** [comment]
5.5 is overall consensus rn, but we are in large agreement that 6 is a good start. to match inbetween, we'll probably go with 5.7

**Comment by CursorDance** [comment]
5.7 should be good enough as a middle ground since cs 4.5Hr is cs5.5 and a good portion of people can do it . soo putting it at 5.7 reduce the amount of map able to reach that and will push people to play less "typical" maps

**Comment by tsunyoku** [comment]
Final decision: 6
