### ISSUE TITLE
Low-AR buff

### ISSUE THREAD

**Issue by CursorDance** [tsunyoku/akatsuki-pp#26]

**Comment by tsunyoku** [comment]
not sure how we’d calculate note density tho, will likely just be an increased buff on low ar

**Comment by kipster16** [comment]
adding onto this, if ez is combined with hd, maybe 1.2x the buff or something?

**Comment by tsunyoku** [comment]
again would be more likely “make hd buff stronger on lower ar”

**Comment by tsunyoku** [comment]
closed by https://github.com/tsunyoku/akatsuki-pp/pull/31
